name: 'Your Action Name'
description: 'Description of your action'
author: 'Your Name'

runs:
  using: 'node20'  # Use Node.js 20 as the runtime environment
  main: 'dist/test.js'  # Specify the path to the entry JavaScript file
